fos_rest:
  body_listener: true
  format_listener:
    enabled: true
    rules:
      - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
      - { path: '^/', stop: true } # Available for version >= 1.5